name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File
    steps:
        - name: executing remote ssh commands
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}
        script: whoami
        - name: Checkout Project A
          uses: actions/checkout@v2
          with:
            path: ./projectA
        - name: Checkout Project B
          run: |
            ls ./projectA
            mkdir ./plotly_project_folder
            cp -R ./projectA/app.py ./plotly_project_folder
            cd ./plotly_project_folder
            git init
            git config --global user.email "ding.luo@shell.com"
            git config --global user.name "Ding Luo"
            git remote add plotly ssh://dokku@dash-dev.selfservice.shell.ai:3022/mining-sites-dashboard
            git status
            git diff
            git add .
            git commit -m "commit from github action"
            git push plotly master
#
#        - name: Copy/Create file
#          run: |
#            FILE=./projectA/file
#            if [ -f "$FILE" ]; then
#              echo "Copying $FILE"
#              cp -R ./projectA/file ./projectB
#            else
#              echo "Creating $FILE"
#              touch ./projectB/file
#            fi
#
#        - name: Push Project B
#          run: |
#            cd ./projectB
#            git add .
#            git config user.name github-actions
#            git config user.email github-actions@github.com
#            git commit -am "File Replicated from Project A"
#            git push
