name: plotly dash enterprise deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
#      - name: Install SSH key of bastion
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_DEPLOY_KEY }}
#          known_hosts: 'placeholder'
##          known_hosts: ${{ secrets.KNOWN_HOST }}
#          config: ${{ secrets.CONFIG }} # ssh_config; optional
#          name: github_actions
#          config: |
#            Host dash-dev.selfservice.shell.ai
#                Port 3022
#            IdentityFile /home/runner/.ssh/id_rsa
      - name: check ssh
        run: |
          echo "${{ secrets.CONFIG }}" >> /home/runner/.ssh/config
          echo "${{ secrets.KNOWN_HOST }}" >> /home/runner/.ssh/known_hosts
          ls -a /home/runner/.ssh/
          cat /home/runner/.ssh/config
          cat /home/runner/.ssh/known_hosts
#          cat /home/runner/.ssh/id_rsa
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: ./original_folder
      - name: Checkout Project B
        run: |
          ls ./original_folder
          mkdir ./plotly_project_folder
          cp -R ./original_folder/app.py ./plotly_project_folder
          cp -R ./original_folder/Procfile ./plotly_project_folder
          cp -R ./original_folder/requirements.txt ./plotly_project_folder
          cd ./plotly_project_folder
          git init
          git config --global user.email "ding.luo@shell.com"
          git config --global user.name "Ding Luo"
          git remote add plotly dokku@dash-dev.selfservice.shell.ai:new-test-app
          git status
          git diff
          git add .
          git commit -m "commit from github action"
          git push plotly master
