name: plotly dash enterprise deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: Install SSH key of bastion
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          name: github_actions
          config: |
            Host dash-dev.selfservice.shell.ai
            Port 3022
            IdentityFile ~/.ssh/github_actions
        - name: Checkout current repo
          uses: actions/checkout@v2
          with:
            path: ./original_folder
        - name: Checkout Project B
          run: |
            ls ./original_folder
            mkdir ./plotly_project_folder
            cp -R ./original_folder/app.py ./plotly_project_folder
            cd ./plotly_project_folder
            git init
            git config --global user.email "ding.luo@shell.com"
            git config --global user.name "Ding Luo"
            git remote add plotly ssh://dokku@dash-dev.selfservice.shell.ai:3022/mining-sites-dashboard
            git status
            git diff
            git add .
            git commit -m "commit from github action"
            git push plotly master
#
#        - name: Copy/Create file
#          run: |
#            FILE=./projectA/file
#            if [ -f "$FILE" ]; then
#              echo "Copying $FILE"
#              cp -R ./projectA/file ./projectB
#            else
#              echo "Creating $FILE"
#              touch ./projectB/file
#            fi
#
#        - name: Push Project B
#          run: |
#            cd ./projectB
#            git add .
#            git config user.name github-actions
#            git config user.email github-actions@github.com
#            git commit -am "File Replicated from Project A"
#            git push
